# esp32:
#   board: esp32-p4-evboard
#   flash_size: 16Mb
#   cpu_frequency: 360MHz
#   framework:
#     type: esp-idf
#     advanced:
#       enable_idf_experimental_features: yes
#       disable_vfs_support_termios: false
#       disable_vfs_support_select: false
#       disable_vfs_support_dir: false
#     sdkconfig_options:
#       CONFIG_SPIRAM_XIP_FROM_PSRAM: "y"   # Stop screen flashing during OTA
#       CONFIG_SDMMC_HOST_DEFAULT: "y"

# # psram:
# #   mode: hex
# #   speed: 200MHz

# esp_ldo:
#   - channel: 3
#     id: dsi_phy_enable
#     voltage: 2.5V
#     adjustable: True

# esp32_hosted:
#   active_high: true
#   variant: ESP32C6
#   reset_pin: GPIO54
#   cmd_pin: GPIO19
#   clk_pin: GPIO18
#   d0_pin: GPIO14
#   d1_pin: GPIO15
#   d2_pin: GPIO16
#   d3_pin: GPIO17

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.5.0
  name_add_mac_suffix: false
  on_boot:
    then:
      # read the RTC time once when the system boots
      rx8130.read_time:
  includes:
    - va_helpers.h

ota:
  - id: ota_esphome
    platform: esphome
    on_begin: 
      then:
        - lvgl.widget.show: updating_screen
        - logger.log:
            level: INFO
            format: "OTA Start"
        - lvgl.widget.redraw: updating_screen

api:
  id: ha_api
  homeassistant_services: true
  # on_client_connected:
  #   - script.execute: draw_display
  #   - lambda: |-
  #       if (!id(boot_sound_played)) {
  #         id(boot_sound_played) = true;
  #         if (id(startup_sound_switch).state) {
  #           id(play_sound)->execute(true, id(ready_sound));
  #         }
  #       }
  #   - script.execute: reset_screensaver
  # on_client_disconnected:
  #   - script.execute: draw_display

captive_portal:

http_request:

logger:
  level: DEBUG


psram:
  mode: hex
  speed: 200MHz

# --- BUSES / PERIPHERALS ------------------------------------------------------
i2c:
  - id: bus_a
    sda: GPIO7
    scl: GPIO8
    scan: true
    frequency: 400kHz

  - id: sensor_bus
    sda: GPIO46
    scl: GPIO45

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO10
    i2s_bclk_pin: GPIO12
    i2s_mclk_pin: GPIO13

audio_dac:
  - platform: es8311
    id: es8311_dac
    i2c_id: bus_a

audio_adc:
  - platform: es7210
    id: es7210_adc
    i2c_id: bus_a
    address: 0x36

# --- TOUCHSCREEN --------------------------------------------------------------
touchscreen:
  - id: my_touchscreen
    platform: gt911
    display: main_display
    i2c_id: bus_a
    interrupt_pin: GPIO21
    reset_pin: GPIO22

    on_release:
      then:
        - logger.log: "Touch released"
        - if:
            condition: lvgl.is_paused
            then:
              - lvgl.resume:
              - lvgl.widget.redraw:

# --- AUDIO DEVICES ------------------------------------------------------------
switch:
  - platform: gpio
    name: Speaker Enable
    icon: "mdi:speaker"
    entity_category: config
    pin: GPIO11
    restore_mode: ALWAYS_OFF

microphone:
  - platform: i2s_audio
    id: box_mic
    i2s_audio_id: i2s_audio_bus
    i2s_din_pin: GPIO48
    sample_rate: 16000
    bits_per_sample: 16bit
    adc_type: external
    channel: stereo

speaker:
  - platform: i2s_audio
    id: box_speaker
    i2s_audio_id: i2s_audio_bus
    i2s_dout_pin: GPIO9
    audio_dac: es8311_dac
    dac_type: external
    channel: mono
    buffer_duration: 100ms
    bits_per_sample: 16bit
    sample_rate: 48000

  - platform: mixer
    id: mixing_speaker
    output_speaker: box_speaker
    # num_channels: 2
    source_speakers:
      - id: announcement_mixer_input
      - id: media_mixer_input

  - platform: resampler
    id: media_resampling_input
    output_speaker: media_mixer_input
    sample_rate: 48000

  - platform: resampler
    id: announcement_resampling_input
    output_speaker: announcement_mixer_input    
    sample_rate: 48000

media_player:
  - platform: speaker
    name: "ESP32 P4 Media Player"
    id: external_media_player
    codec_support_enabled: true
    volume_min: 0.5
    volume_max: 0.75 # don't go higher than 0.8
    volume_increment: 0.05
    volume_initial: 0.6

    announcement_pipeline:
      speaker: announcement_resampling_input
      format: FLAC
      num_channels: 1
      sample_rate: 48000

    media_pipeline:
      speaker: media_resampling_input
      format: FLAC
      num_channels: 1
      sample_rate: 48000
    buffer_size: 250000

    on_announcement:
      - if:
          condition:
            - microphone.is_capturing:
          then:
            - script.execute: stop_wake_word
            - if:
                condition:
                  - lambda: return id(wake_word_engine_location).current_option() == "In Home Assistant";
                then:
                  - wait_until:
                      condition:
                        - not:
                            voice_assistant.is_running:

      - if:
          condition:
            lambda: 'return id(playing_internal_sound);'
          then:
            - lambda: 'id(playing_internal_sound) = false;'
          else:
            - script.execute: reset_screensaver

    on_play:
      - if:
          condition:
            - microphone.is_capturing:
          then:
            - script.execute: stop_wake_word
            - if:
                condition:
                  - lambda: return id(wake_word_engine_location).current_option() == "In Home Assistant";
                then:
                  - wait_until:
                      condition:
                        - not:
                            voice_assistant.is_running:

      - if:
          condition:
            lambda: 'return id(playing_internal_sound);'
          then:
            - lambda: 'id(playing_internal_sound) = false;'
          else:
            - script.execute: reset_screensaver

    on_pause:
      - if:
          condition:
            not:
              voice_assistant.is_running:
          then:
            - script.execute: start_wake_word
            - script.execute: set_idle_or_mute_phase

    on_idle:
      - if:
          condition:
            not:
              voice_assistant.is_running:
          then:
            - script.execute: start_wake_word
            - script.execute: set_idle_or_mute_phase

    files:
      - id: timer_finished_sound
        file: https://github.com/RealDeco/xiaozhi-esphome/raw/main/sounds/timer_finished.flac
      - id: wake_word_triggered_sound
        file: https://github.com/RealDeco/xiaozhi-esphome/raw/main/sounds/wake_word_triggered.flac
      - id: ready_sound
        file: https://github.com/RealDeco/xiaozhi-esphome/raw/main/sounds/${startup_sound}.flac

# --- DISPLAY DRIVER (MIPI SPI JC3636W518) ------------------------------------
display:
  - platform: mipi_dsi
    id: main_display
    model: JC1060P470
    update_interval: never
    reset_pin:
      number: GPIO05
    hsync_pulse_width: 20
    auto_clear_enabled: false
    # rotation: ${rotate_display}
