substitutions:
  name: guition-p4-70
  friendly_name: Guition P4 70

## Modular version Main P4

## SETTINGS ######################################################################################################################################

  imagewidth:  "400"
  imageheight: "600"

  screenwidth:  "1024"
  screenheight: "600"
  rotate_display: "0"

  startup_sound: "Home_Connected" # (options are: available, Home_Connected, Home_Connected_Male, Computer_Ready)
  clock_background_image: "starrysky" # (options are: clock, hacker, mission, starrysky, waves, tron, chip)
  imagemodel: "Gwen" # options are: Gwen

# USE ONLINE OR LOCAL MODEL AND WALLPAPER IMAGES, IMAGES SHOULD BE PLACED IN homeassistant/www/imagas/
  imagepath: "https://github.com/RealDeco/xiaozhi-esphome/raw/main/images"
#  imagepath: "http://homeassistant.local:8123/local/images/"

  weather_entity: "weather.forecast_home"

##################################################################################################################################################

  font_glyphsets: "GF_Latin_Kernel"
  # font_glyphsets: "GF_Latin_Core"
  font_family: Fraunces

esp32:
  board: esp32-p4-evboard
  flash_size: 16Mb
  cpu_frequency: 360MHz
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: yes
      disable_vfs_support_termios: false
      disable_vfs_support_select: false
      disable_vfs_support_dir: false
    sdkconfig_options:
      CONFIG_SPIRAM_XIP_FROM_PSRAM: "y"   # Stop screen flashing during OTA
      CONFIG_SDMMC_HOST_DEFAULT: "y"

psram:
  mode: hex
  speed: 200MHz

esp_ldo:
  - channel: 3
    id: dsi_phy_enable
    voltage: 2.5V
    adjustable: True

esp32_hosted:
  active_high: true
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17

logger:
  level: DEBUG

### USE MODULES FROM GITHUB (default) ############################################################################################################

# packages:
#   core:
#     url: https://github.com/RealDeco/xiaozhi-esphome.git
#     ref: main
#     refresh: 0s
#     files:
#       - devices/Under_Development/Modular/core.yaml
#   hw:
#     url: https://github.com/RealDeco/xiaozhi-esphome.git
#     ref: main
#     refresh: 0s
#     files:
#       - devices/Under_Development/Modular/HW/guition_7.0_hw.yaml

### USE LOCAL MODULES (read description https://github.com/RealDeco/xiaozhi-esphome/blob/main/devices/Under_Development/Modular/README.md) #######

packages: # Local
 core: !include localtest/core-lvgl.yaml
 hw:   !include localtest/HW/hw-lvgl.yaml
#  core: !include localtest/core.yaml
#  hw:   !include localtest/HW/guition_7.0_hw.yaml

## ENABLE / DISABLE WAKE WORDS ## IF LOW ON MEMORY, USE LESS WAKE WORDS ##########################################################################

micro_wake_word:
  id: mww
  models:
    - okay_nabu

##################################################################################################################################################

# i2c air:
#   - id: sensor_bus
#     sda: GPIO46
#     scl: GPIO45
    
# sensor:
#   - id: sen55
#     platform: sen5x
#     i2c_id: sensor_bus
#     pm_1_0:
#       name: PM <1µm Weight concentration
#     pm_2_5:
#       name: PM <2.5µm Weight concentration
#     pm_4_0:
#       name: PM <4µm Weight concentration
#     pm_10_0:
#       name: PM <10µm Weight concentration
#     temperature:
#       name: Temperature
#     humidity:
#       name: Humidity
#     voc:
#       name: VOC
#     nox:
#       name: NOX
